# Generated by Django 2.2.3 on 2019-08-01 05:58
import apps

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='apps_celeryscan',
            fields=[
                ('id_key', models.AutoField(primary_key = True)),
                ('json_results', models.CharField(max_length = 20000, null=True, blank=True)),
                ('is_complete', models.BooleanField(default = False)),
            ],
        ),
        migrations.CreateModel(
            name='apps_filemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save_name', models.FileField(upload_to=apps.file_upload_path_for_db)),
                ('file_origin_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('file_ext', models.CharField(max_length=10)),
                ('is_img', models.BooleanField(default=False)),
            ],
            options={
                #'db_table': 'file_boxes',
                'ordering': ['create_date'],
            },
        ),
       
    ]
